### PR TITLE
Image link correction

### LINKED ISSUE #21: readme images link to image file when they shouldnt.
readme images link to the image file when they should link to the duckmath.org and the discord server. need done asap.

### PR DESCRIPTION
**Pull request by An-Array**
closes #21

### CODE REVIEW

**Review by maddox05 — CHANGES_REQUESTED** [review]
please make sure to test your code before pushing, this does not work. looks like it should but in testing it does not.

**Comment by maddox05** [comment]
yeah it works normally but when used on github it does not, maybe github changed linking?

**Comment by An-Array** [comment]
Can you check again? @maddox05 I have changed the syntax.

**Comment by maddox05** [comment]
still does not work but ima merge cuz idk what the problem is.

**Comment by An-Array** [comment]
@maddox05 It works on your repo now. I just tried 🙂

**Comment by maddox05** [comment]
i just fixed it yeah was a problem from who originally did it, thanks for the help!

**Pull request merged**
