### PR TITLE
Issue 15 - Updated Recommended Section

### PR DESCRIPTION
**Pull request by DavidRod1865**
#15 - Updated Recommended Section using JS and CSS. Also, updated some CSS that was conflicting with the layout of the recommended section.

### CODE REVIEW

**Review by maddox05 — CHANGES_REQUESTED** [review]
looks really good honestly, just push it back down to where it was before and change the font of the bottom warning message back to what it was, the red is a fine color though.

**Comment by DavidRod1865** [comment]
@maddox05 - I made the request changes. Let me know if everything looks fine now.

**Comment by maddox05** [comment]
hi! you pushed the title up, it needs to be in the same place. other than that reccomened is in the correct place. Just put the title back to where it originally was and you are all good! -Thanks!

**Review by maddox05 — CHANGES_REQUESTED** [review]
look at comment above

**Pull request closed without merging**
