### PR TITLE
style(navbar): add aesthetic blur

### PR DESCRIPTION
**Pull request by rasvanjaya21**
I have finished the feature 🔥

## Summary by CodeRabbit

- **New Features**
	- Enhanced styling for the top navigation bar, including a blur effect on scroll.
	- Introduced interactive image in the navigation bar with hover effects.
	- Updated dropdown menu to include "G4m3 Requests" and made "Virtual Machines" visible.

- **Bug Fixes**
	- Adjusted hover state for dropdown links for better user interaction.

- **Style**
	- Added fallback background color for better compatibility.
	- Refined styles for dropdown menus in both desktop and mobile views.

### CODE REVIEW

**Comment by maddox05** [comment]
duckmath header moves kinda wierd when switching from normal to overthe apps, also more does not work when apps are hovered over, for ex if i scroll down a ton more does not fully show.

**Review by maddox05 — CHANGES_REQUESTED** [review]
changes in comment of this pr

**Comment by rasvanjaya21** [comment]
Thanks for correction, I have updated my pr as the suggestion

**Review by maddox05 — APPROVED** [review]
LGTM

**Pull request merged**
