### PR TITLE
Added a button to the navbar when the screen size shrinks to mobile v…

### PR DESCRIPTION
**Pull request by SumitVerma-coder**
Now the topnav merges into a button on mobile view.
image
image

### CODE REVIEW

**Comment by maddox05** [comment]
the top nav switches to the drop down but the drop down does not work.

**Review by maddox05 — CHANGES_REQUESTED** [review]
Needs topnav drop down to be working on both mobile and desktop, it does not work on both.

**Comment by SumitVerma-coder** [comment]
I am looking into it.

**Comment by SumitVerma-coder** [comment]
Fixed the issue. Please look into it.

**Comment by maddox05** [comment]
Via the most recent deployment clicking the new drop down does nothing.

**Comment by SumitVerma-coder** [comment]
It is working perfectly in my local machine. Can you specify the issue.

**Comment by maddox05** [comment]
ima just merge it lol.

**Pull request merged**
